### ISSUE TITLE
14º Desafio: Elaboração de um Layout básico para um negócio genérico - Peso 3

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#17]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

**Para esse desafio, pedimos que os negocio genericos, sejam escolhidos apartir dos arquivos PDF's fornecidos. Além disso, as 17 primeiras respostas serão aceitas e pontuadas no ranking das equipes.**
[GRUPOS - 3º ANO A.pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10911463/GRUPOS.-.3.ANO.A.pdf)
[Grupos BD - 3B.pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10911475/Grupos.BD.-.3B.pdf)

Um dos desafios mais comuns que os alunos de programação enfrentam é a criação de um layout para um site de negócios genérico. Embora possa parecer uma tarefa simples, a criação de um design eficaz pode ser um processo complexo e demorado.

O primeiro passo para criar um layout de site é entender a finalidade do site e seu público-alvo. Para isso, deve-se fazer uma pesquisa para descobrir quais são as necessidades e desejos dos usuários em potencial. Deve-se considerar as características da marca e como elas devem ser representadas no design do site.

Depois de entender o objetivo do site, o próximo passo é criar um esboço do layout. Deve-se pensar em como os diferentes elementos do site serão organizados na página, incluindo o cabeçalho, rodapé, menu de navegação, seções de conteúdo e call-to-actions. É importante que o design seja limpo, organizado e fácil de navegar para o usuário.

Após o esboço do layout, deve-se começar a trabalhar no design visual do site. Deve-se escolher uma paleta de cores que esteja alinhada com a marca e que seja agradável para o usuário. É importante também escolher uma tipografia que seja legível e fácil de ler.

Deve-se criar uma estrutura visual para o site, incluindo imagens, ícones e gráficos. É importante que esses elementos estejam em harmonia com o restante do design do site.

Uma vez que o layout esteja pronto, deve-se testar o site em diferentes navegadores e dispositivos para garantir que o design esteja funcionando corretamente em todas as plataformas. Deve-se se certificar de que o site seja responsivo, ou seja, que seja fácil de usar em dispositivos móveis.

Em resumo, criar um layout eficaz para um site de negócios genérico envolve entender a finalidade do site, criar um esboço do layout, desenvolver um design visual atraente e testar o site em diferentes plataformas. Com esses passos gerais, pode-se criar um site bem projetado e fácil de usar, que atenda às necessidades dos usuários e da marca

### Additional tips

Seja criativo.

**Comment by iurygdeoliveira** [comment]
Não hesitem em solicitar ajuda ao professor, sobre prováveis ferramentas que possam auxiliar no processo

**Comment by gff001** [comment]
### DUO ORCACA
**TEMA: SITE PIZZARIA** 
**Slogan:** _Soy  Francesco Virgulini, lá máquina mas rápida de tote italie!_
[8-PIZZARIA.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10914655/8-PIZZARIA.zip)

**Comment by iurygdeoliveira** [comment]
Ainda serão aceitas, 16 respostas.

**Comment by alinelima28** [comment]
Equipe Autarquia
Tema: Site para Evento Esportivo.
Caso de uso: Interclasse.
[Desafio 14.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10923129/Desafio.14.zip)

**Comment by Analicemc** [comment]
# Equipe Lovelace
Negócio: Fotografia 
O site tem como objetivo servir como portfólio da fotógrafa e também como meio para entrar em contato com ela. Acesse-o no repositório: 
[https://github.com/Analicemc/Layout-de-neg-cio](url)

**Comment by SamuelMRM** [comment]
[Desafio.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10942612/Desafio.zip)
Equipe Flasco

**Comment by kiaraalcantara** [comment]
Equipe: The Makers

> Layout baseado em uma loja online:
> Baixar arquivo: [Layout de  uma loja.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10942713/Layout.de.uma.loja.zip)

**Comment by iurygdeoliveira** [comment]
> Equipe Autarquia Tema: Site para Evento Esportivo. Caso de uso: Interclasse. [Desafio 14.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10923129/Desafio.14.zip)

Resposta aceita

**Comment by iurygdeoliveira** [comment]
> # Equipe Lovelace
> 
> Negócio: Fotografia O site tem como objetivo servir como portfólio da fotógrafa e também como meio para entrar em contato com ela. Acesse-o no repositório: [https://github.com/Analicemc/Layout-de-neg-cio](url)

O link parece está quebrado, poderia corrigir ?

**Comment by iurygdeoliveira** [comment]
> [Desafio.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10942612/Desafio.zip) Equipe Flasco

Resposta aceita

**Comment by iurygdeoliveira** [comment]
> Equipe: The Makers
> 
> > Layout baseado em uma loja online:
> > Baixar arquivo: [Layout de  uma loja.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10942713/Layout.de.uma.loja.zip)

resposta aceita

**Comment by simonebreeman** [comment]
Equipe: Resistech
Alunas: Lorenna Guedes e Simone Breeman

Projeto: Layout Básico de um Açougue Real existente na cidade.

Objetivo: O estabelecimento é um potencial cliente e, por isso, foi feito um layout utilizando suas informações reais com vistas a apresentar a proposta para o proprietário do estabelecimento de maneira que ele possa mais facilmente visualizar o produto (site) e compreender a importância de ter tal ferramenta como meio de expansão do seu negócio.

Justificativa: Após levantamento inicial, verificou-se que o referido estabelecimento comercial na cidade de Araguaína não possui webpage, muito embora faça divulgações no instagram e atenda pedidos por whatsapp. Por já utilizar meios digitais, foi considerado um cliente em potencial na análise de prospecção de negócio.

Link de acesso:

https://drive.google.com/drive/folders/1WcoJ6t60EoxOJDPv6-YhhmAptpMdCI2q?usp=sharing

**Comment by iurygdeoliveira** [comment]
> # Equipe Lovelace
> 
> Negócio: Fotografia O site tem como objetivo servir como portfólio da fotógrafa e também como meio para entrar em contato com ela. Acesse-o no repositório: [https://github.com/Analicemc/Layout-de-neg-cio](url)

Consegui acessar, resposta aceita

**Comment by iurygdeoliveira** [comment]
> Equipe: Resistech Alunas: Lorenna Guedes e Simone Breeman
> 
> Projeto: Layout Básico de um Açougue Real existente na cidade.
> 
> Objetivo: O estabelecimento é um potencial cliente e, por isso, foi feito um layout utilizando suas informações reais com vistas a apresentar a proposta para o proprietário do estabelecimento de maneira que ele possa mais facilmente visualizar o produto (site) e compreender a importância de ter tal ferramenta como meio de expansão do seu negócio.
> 
> Justificativa: Após levantamento inicial, verificou-se que o referido estabelecimento comercial na cidade de Araguaína não possui webpage, muito embora faça divulgações no instagram e atenda pedidos por whatsapp. Por já utilizar meios digitais, foi considerado um cliente em potencial na análise de prospecção de negócio.
> 
> [DESAFIO 14.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10960171/DESAFIO.14.zip)
> 
> ou
> 
> Link de acesso:
> 
> https://drive.google.com/drive/folders/1WcoJ6t60EoxOJDPv6-YhhmAptpMdCI2q?usp=sharing

resposta aceita

**Comment by samuelsamnx** [comment]
Equipe SLR
Alunos: Samuel Teixeira, Luis Felipe Cardoso, Rangerson Clemente

Layout minimalista e básico de uma barbearia local.

https://drive.google.com/file/d/1Jk_YHKaNkcbIJWDl7xA66Ce7eT3rLHlZ/view?usp=sharing

**Comment by iurygdeoliveira** [comment]
> Equipe SLR Alunos: Samuel Teixeira, Luis Felipe Cardoso, Rangerson Clemente
> 
> Layout minimalista e básico de uma barbearia local.
> 
> https://drive.google.com/file/d/1Jk_YHKaNkcbIJWDl7xA66Ce7eT3rLHlZ/view?usp=sharing

resposta aceita
