### ISSUE TITLE
1º Desafio: Como criar uma logo que represente a equipe utilizando o chatgpt + (midjourney ou BlueWillow) -  Peso 1

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#2]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

De maneira concisa, os procedimentos fundamentais deste desafio consistem em utilizar o ChatGPT para criar uma descrição de um logotipo em língua inglesa e, em seguida, com a posse de tal descrição, acessar o Midjourney ou o BlueWillow para gerar as respectivas imagens inserindo a descrição obtida no ChatGPT. 

Uma vez completada a fase de concepção, é crucial inserir a imagem resultante juntamente com uma breve síntese sobre o significado subjacente ao logotipo. Na eventualidade de dificuldades em interpretar o significado da imagem gerada, uma opção válida seria contar com a ajuda de um indivíduo de confiança, cujas competências hermenêuticas possam ser devidamente aproveitadas.

É válido salientar que existem múltiplos parâmetros que podem ser empregados a fim de aprimorar a geração das imagens no Midjourney ou BlueWillow, portanto, é altamente recomendado explorá-los com afinco

**A resposta será somente aceita, se estiver acompanhada de uma descricao passo a passo, demonstrando o passo a passo realizado
pela equipe**

### Additional tips

Sugere-se seguir rigorosamente as diretrizes dessas plataformas, pois caso contrário, pode-se experimentar resultados infelizes e até mesmo emocionalmente dolorosos. Em outras palavras, não se deve permitir que o entusiasmo o conduza para o buraco do coelho, do vasto e imprevisível ciberespaço, que pode ser comparado à alegórica Terra do Nunca.

Além disso, lembre-se, não se deve subestimar os possíveis efeitos colaterais que essa atividade pode desencadear. Um excesso de ousadia pode resultar em desdobramentos extremamente indesejáveis, como um ataque em massa de pixels rebeldes, que podem se rebelar e tomar a forma de espécies hiper-realistas e ameaçadoras nas imagens geradas. Assim sendo, todo cuidado é pouco ao adentrar o vasto e complexo mundo do processamento de imagens por inteligência artificial.

**Comment by edsonjrn** [comment]
https://docs.google.com/document/d/1Ic6u6CnNdJEEgRuSHB4MqxtZy0YkjI20muGQE__i5EQ/edit?usp=sharing

![edilson_hufflepuff_with_slytherin_64c14498-8dc8-4fce-acd4-0f5972848ae5](https://user-images.githubusercontent.com/112779805/221972008-0e25410b-1022-47b8-a4bd-2a704582f399.png)

Nome da equipe: PDF (Pastel De Flango)

**Comment by FilipeCarvalhoC** [comment]
[https://docs.google.com/document/d/1MX2anu-UEECey9ukmxVYhJZzw1lan0l8J0TxSTiklV8/edit](url)
![Vikings](https://user-images.githubusercontent.com/104224266/221978047-6ed98b21-b67b-49e8-9fc0-9c7ce0c0e8c3.png)

Nome Equipe: Vikings

**Comment by rafaelnamel0** [comment]
Nome da equipe: ThreeCoders
![ThreeCodersLOGO](https://user-images.githubusercontent.com/124813972/221979094-55f19916-3759-48b8-a27d-8b6a374bb2e0.jpg)
`

**Comment by byancamamedes** [comment]
https://docs.google.com/document/d/1KHstbjCvz40gcdxUyV1hxO6NkDhg7WEEZqX-yMcGH6w/edit?usp=sharing
![logo](https://user-images.githubusercontent.com/126615587/221997826-e5b93bd2-6068-469a-abac-9e50f12d9dbc.png)

**Comment by ju-santana** [comment]
https://docs.google.com/document/d/19-AiqVMXZ5htNPQbwHgWELsx-sMXsFshB7rlvU25DPs/edit?usp=sharing
Nome da Equipe: Valkyrie(Valquirias)
![ju_sweetzr_three_curly_warrior_women_8bf578c5-1959-4704-bb64-a3a430db2352](https://user-images.githubusercontent.com/126616010/222003694-3a12bbb7-a6c4-413e-88f6-edae70504479.png)

**Comment by Milhomem1996** [comment]
https://docs.google.com/document/d/e/2PACX-1vST1T2BGND7GrfV_juPdupci-jGC0PI3QK1jp6TP5yNgtHjFrW25KtgvNzLVzbhJVnc5qYym14IUnEf/pub
Nome da Equipe: AlfaTech

![LOGO](https://user-images.githubusercontent.com/126627096/222012786-7d646b93-9fce-4893-b102-83bdadbd81c2.png)

**Comment by Monalisa-Gama** [comment]
Equipe: Phytomancers

Abrimos o site do Midjourney e entramos no servidor do discord deles 

No servidor do discord geramos a imagem com a seguinte frase: "emblem of a potion simple "

![phytomancers](https://user-images.githubusercontent.com/70865536/222015232-d17df70c-caf6-421f-a9b7-07cafaa9f657.png)

**Comment by gff001** [comment]
NOME DA EQUIPE: G.A
![LOGO_FINAL](https://user-images.githubusercontent.com/126627187/222016341-f2afe36c-8d27-46b7-b0f8-f1de6d359a3a.jpg)

**Comment by mouraronald** [comment]
Equipe: InfoElectric
Abrimos a plataforma Midjourney  e entramos no discord
No discord geramos a imagem com o seguinte comando:"Electric".

![ronny](https://user-images.githubusercontent.com/126627313/222016644-4c44a6da-a1a3-4c13-8d99-354b24f9450c.png)

**Comment by Analicemc** [comment]
Descrição:
[https://docs.google.com/document/d/15FpPWQnhDlPaGqRX2frw_0PKxtguZAuuBXRiGGuo6wk/edit?usp=sharing](url)
![lovelace](https://user-images.githubusercontent.com/87390603/222015273-11a6a10f-c486-43ab-8c67-c06b2e613282.png)
Nome: Equipe Lovelace
Componentes: Analice e Suzana

**Comment by Edubssousa** [comment]
https://docs.google.com/document/d/e/2PACX-1vSoAQU7Ky-3QIqmgvzvsEtiVfjF9n3u24eICChIfJEKJgv_R4l6XKCt6TZCF_UdSzgGDvy7LLa3T0uf/pub
![ApenasUmEduardo_create_an_image_of_three_male_different_dragon__da435363-1135-4bf6-afd3-f878dbba0c8e](https://user-images.githubusercontent.com/126627044/222017729-f25304ad-8fe3-4bcc-8cdd-ae94f10ba351.png)

**Comment by samuelsamnx** [comment]
https://docs.google.com/document/d/1kGLN4GcxIjv79A5NNXL3Z0nwSKSmfYM3obt6OLHDC7E/edit?usp=sharing

Nome da equipe: SLR

Integrantes: Samuel Teixeira, Luis Felipe e Rangerson Clemente

![SLR](https://user-images.githubusercontent.com/126624010/222017767-e9366c92-f597-483f-90d0-dd809d1cc015.png)

**Comment by Keziopb** [comment]
https://docs.google.com/document/d/1Az-IqzUvO0jOzNaLMvrkD2JgmX12Gv3fGXwbrHHI5vM/edit

![image](https://user-images.githubusercontent.com/126627347/222017875-1496a042-2bef-477d-8a04-70568bd1cba2.png)

Equipe: NetForce
Integrante: José victor, Kezio

**Comment by simonebreeman** [comment]
EQUIPE **RESISTECH**

Lorenna Guedes e Simone Breeman

![Resistech](https://user-images.githubusercontent.com/126627160/222018558-8060434a-3218-493c-93ea-08b7fa2981eb.jpg)












Descrição passo a passo, demonstrando o processo de criação realizado pela equipe:
https://docs.google.com/document/d/1NcDo-8H4nczGi4Ov7-VnSTJHH4OjsE19ExFyh_N2C7U/edit?usp=sharing

**Comment by Alylol** [comment]
Segue em anexo a imagem do grupo e o passo-a-passo de como foi feita
[Relatório de desenvolvimento.docx](https://github.com/iurygdeoliveira/Web-development-classes/files/10856044/Relatorio.de.desenvolvimento.docx)
![cyber warriors](https://user-images.githubusercontent.com/108137566/222018706-9b596b2d-f6c8-4b64-a123-663b9e274441.png)

**Comment by Atorvic** [comment]
Nome da equipe: Pro-Dog-IA

![logogithub](https://user-images.githubusercontent.com/115494201/222018923-cde995be-ed73-4619-858a-4e67b5f1c478.jpg)

[Passo a passo .docx](https://github.com/iurygdeoliveira/Web-development-classes/files/10856058/Passo.a.passo.docx)

**Comment by adielsondantas** [comment]
![adielsoneeduarda](https://user-images.githubusercontent.com/126627177/222019054-f1ee3767-26b1-4c31-8777-52ed593e9c83.png)

https://docs.google.com/document/d/1h9zYzkcMs-q36K4T5Rf6jMBr66GpBW7XVzRgW0Mku5w/edit?usp=sharing

**Comment by Saah25** [comment]
Nome da Equipe: As Três Mosqueteiras 

Passo a passo: https://docs.google.com/document/d/1O2BK8z_8g7WbFWepONrbBWLZJFBDmXsYHNNe5E6KuQ8/edit?usp=sharing

![Logomarca](https://user-images.githubusercontent.com/126616901/222208940-5bee8c7e-3b0c-4573-b3dd-3ab230f14849.png)

**Comment by iurygdeoliveira** [comment]
> https://docs.google.com/document/d/1NFp2va0-2PMmQ_OK2ftOGM6Ugm1aLBO-A4m_TkXl5J4/edit?usp=sharing ![paulosamuelabraim_The_logo_features_a_trident_a_symbol_that_is__542c07c4-89af-43f0-8f62-78fa79508e49](https://user-images.githubusercontent.com/126599155/221930210-d864c6cb-57fe-45bd-8352-bee0ef1100e5.png)
> 
> Professor segue o desafio. O nome da nossa equipe é: Flasco



> 

Ola alunos, tudo certo, vcs pontuaram nesse desafio

**Comment by iurygdeoliveira** [comment]
> https://docs.google.com/document/d/1Ic6u6CnNdJEEgRuSHB4MqxtZy0YkjI20muGQE__i5EQ/edit?usp=sharing
> 
> ![edilson_hufflepuff_with_slytherin_64c14498-8dc8-4fce-acd4-0f5972848ae5](https://user-images.githubusercontent.com/112779805/221972008-0e25410b-1022-47b8-a4bd-2a704582f399.png)
> 
> Nome da equipe: PDF (Pastel De Flango)

Não consigo acessar o tutorial de vcs, por favor liberem o acesso para eu corrigir, coloquem ele como acesso público

**Comment by iurygdeoliveira** [comment]
> [Passo a passo](https://docs.google.com/document/d/1MX2anu-UEECey9ukmxVYhJZzw1lan0l8J0TxSTiklV8/edit) ![Vikings](https://user-images.githubusercontent.com/104224266/221978047-6ed98b21-b67b-49e8-9fc0-9c7ce0c0e8c3.png)
> 
> Nome Equipe: Vikings

Pessoal, alterar o passo a passo para acesso publico, não consigo acessar o passo a passo.

**Comment by Saah25** [comment]
Nome da Equipe: As Três Mosqueteiras

https://docs.google.com/document/d/1O2BK8z_8g7WbFWepONrbBWLZJFBDmXsYHNNe5E6KuQ8/edit?usp=sharing

![Logomarca (1)](https://user-images.githubusercontent.com/126616901/222215476-d396faa6-d297-4782-97cb-e848757ee269.png)

**Comment by iurygdeoliveira** [comment]
> https://docs.google.com/document/d/1Ic6u6CnNdJEEgRuSHB4MqxtZy0YkjI20muGQE__i5EQ/edit?usp=sharing
> 
> ![edilson_hufflepuff_with_slytherin_64c14498-8dc8-4fce-acd4-0f5972848ae5](https://user-images.githubusercontent.com/112779805/221972008-0e25410b-1022-47b8-a4bd-2a704582f399.png)
> 
> Nome da equipe: PDF (Pastel De Flango)

corrigido

**Comment by RenataGomes123** [comment]
NOME DA EQUIPE: GODDESSES OF CODING

https://docs.google.com/document/d/1uuMulbGnSdwWMcQS2lL6d8CjMz2AVoA9pX1M8a2vneY/edit?usp=sharing

![Desafio 1 F](https://user-images.githubusercontent.com/126616099/222216318-57b2ddb5-97fd-46dc-8042-5ce11ed24fb5.png)

**Comment by yasmincosta21** [comment]
NOME DA EQUIPE: ABY (Iniciais dos nossos nomes);
DOCUMENTO COM O PASSO A PASSO:
https://docs.google.com/document/d/1T38A7jxN05zVvmJgznUnUuR_-W3wu1bT1iPMaknICsg/edit?usp=sharing
LOGOTIPO:
![final](https://user-images.githubusercontent.com/126615967/222216424-e1733bc0-cfef-4803-9bcc-6fe73cdb9cce.png)

**Comment by iurygdeoliveira** [comment]
> # Equipe ThreeCoders
> 
> ![221979094-55f19916-3759-48b8-a27d-8b6a374bb2e0](https://user-images.githubusercontent.com/124813972/222093110-ffe3ceb6-79e2-45ab-87d2-0249e9ea51c4.jpg)
> 
> [Confira o passo-a-passo](https://docs.google.com/document/d/1ZCwwoddKmvGYhrpzOQFsyFwlxr2E3MHv8085X1kNbv0/edit)

Corrigido

**Comment by iurygdeoliveira** [comment]
> https://docs.google.com/document/d/1KHstbjCvz40gcdxUyV1hxO6NkDhg7WEEZqX-yMcGH6w/edit?usp=sharing ![logo](https://user-images.githubusercontent.com/126615587/221997826-e5b93bd2-6068-469a-abac-9e50f12d9dbc.png)

corrigido

**Comment by iurygdeoliveira** [comment]
> 

Qual a turma e o nome das integrantes da equipe ?

**Comment by iurygdeoliveira** [comment]
> https://docs.google.com/document/d/19-AiqVMXZ5htNPQbwHgWELsx-sMXsFshB7rlvU25DPs/edit?usp=sharing Nome da Equipe: Valkyrie(Valquirias) ![ju_sweetzr_three_curly_warrior_women_8bf578c5-1959-4704-bb64-a3a430db2352](https://user-images.githubusercontent.com/126616010/222003694-3a12bbb7-a6c4-413e-88f6-edae70504479.png)

Qual o nome das integrantes da equipe, e de qual turma ?

**Comment by iurygdeoliveira** [comment]
> https://docs.google.com/document/d/e/2PACX-1vST1T2BGND7GrfV_juPdupci-jGC0PI3QK1jp6TP5yNgtHjFrW25KtgvNzLVzbhJVnc5qYym14IUnEf/pub Nome da Equipe: AlfaTech
> 
> ![LOGO](https://user-images.githubusercontent.com/126627096/222012786-7d646b93-9fce-4893-b102-83bdadbd81c2.png)

corrigido

**Comment by iurygdeoliveira** [comment]
> 

Qual o nome dos integrantes da equipe e a turma ?

**Comment by iurygdeoliveira** [comment]
> 

corrigido

**Comment by iurygdeoliveira** [comment]
> > https://docs.google.com/document/d/1Ic6u6CnNdJEEgRuSHB4MqxtZy0YkjI20muGQE__i5EQ/edit?usp=sharing
> > ![edilson_hufflepuff_with_slytherin_64c14498-8dc8-4fce-acd4-0f5972848ae5](https://user-images.githubusercontent.com/112779805/221972008-0e25410b-1022-47b8-a4bd-2a704582f399.png)
> > Nome da equipe: PDF (Pastel De Flango)

> NOME DA EQUIPE: G.A ![LOGO_FINAL](https://user-images.githubusercontent.com/126627187/222016341-f2afe36c-8d27-46b7-b0f8-f1de6d359a3a.jpg)

Onde está o passo a passo ?  Onde está o nome dos integrantes da equipe ? De qual turma ?

**Comment by iurygdeoliveira** [comment]
> NOME DA EQUIPE: G.A ![LOGO_FINAL](https://user-images.githubusercontent.com/126627187/222016341-f2afe36c-8d27-46b7-b0f8-f1de6d359a3a.jpg)

Onde está o passo a passo ? Onde está o nome dos integrantes da equipe ? Qual é a turma ?

**Comment by iurygdeoliveira** [comment]
> Equipe: InfoElectric Abrimos a plataforma Midjourney e entramos no discord No discord geramos a imagem com o seguinte comando:"Electric".
> 
> ![ronny](https://user-images.githubusercontent.com/126627313/222016644-4c44a6da-a1a3-4c13-8d99-354b24f9450c.png)

Qual o nome dos integrantes da equipe ? Qual a turma ? Qual o nome da equipe ?

**Comment by iurygdeoliveira** [comment]
> 

O acesso ao passo a passo está negado, favor liberar acesso para que eu possa fazer a correção

**Comment by duda2010** [comment]
https://docs.google.com/document/d/1WmVcO9XFMaTm6zweX8RH9wcUmzb1251KqODYgLCgZfk/edit?usp=sharing
![ghenry-san_blue_fire_phoenix_red_and_black_background_9b2ff2f7-c86b-4bac-852d-68914902fc6e](https://user-images.githubusercontent.com/126600993/222226395-2c639c4a-32d3-4eb6-bbeb-8db03aaf16d1.png)

**Comment by nandsray** [comment]
![RayRay_logo_A_powerful_embodiment_of_Medusa_with_green_features_ab0a2415-2e43-49f3-ab76-81894085664c](https://user-images.githubusercontent.com/126599226/222228297-68d3580c-cf65-4c39-9502-319ad7e4a47a.png)
3° B de Informática/Integrantes: Rayssa Auder e Beatriz dos Santos.
Nome da equipe: Medusas
https://docs.google.com/document/d/1U5rqEL0oQbRsBY0YQE-oz1LMhufEHEzO8MZlAB6fKpc/edit?usp=sharing

**Comment by raykagomess** [comment]
![f676a27b-3b96-456b-bf3b-8e87dfabc3f7](https://user-images.githubusercontent.com/126599365/222232792-88754359-5844-4ddd-94ee-416ed6e715f8.jpg)
Nome da Equipe: FIX (Fênix)
Entramos no ChatGPT e pedimos para ser criada a descrição da logo baseada em uma fenix
Depois entramos no Discord do BlueWillow e geramos a imagem baseada na descrição do ChatGPT com o comando /imagine.
Membros: Rayka Gomes, Marcos Luiz e Rita de Kassia

**Comment by lukasaraujom** [comment]
![escolalukasemuriel4](https://user-images.githubusercontent.com/126599288/222233767-9fb43795-3b16-4e6c-b2d9-2088b4ec2e50.jpg)
Nome da equipe: As Negrinhas 
Entramos no site ChatGPT e solicitamos a descrição em base de uma logo escolar. Logo após entramos no aplicativo Discord do BLUEWILLOW e criamos a imagem baseada na descrição do CHATGPT com o comando /imagine.
Integrantes do grupo: Lucas e Muriel.

**Comment by ileandraa** [comment]
Nome da equipe: Filhos de Odin
Integrantes: Kaillany Maria, William Dias e Leandra Costa

1º passo: Entramos no ChatGPT e pedimos para descrever uma imagem de Loki
2º passo: Copiamos a descrição e colamos no chatbot do discord do canal do MidJourney e foi gerada a nossa imagem

[https://drive.google.com/file/d/1o8urGoFWqjWrfn40tGm1b5eA8mVP4K8C/view?usp=sharing](url)

**Comment by ileandraa** [comment]
Nome da equipe: Filhos de Odin
Integrantes: Kaillany Maria, William Dias e Leandra Costa

1º passo: Entramos no ChatGPT e pedimos para descrever uma imagem de Loki
2º passo: Copiamos a descrição e colamos no chatbot do discord do canal do MidJourney e foi gerada a nossa imagem

![filhosdeodin](https://user-images.githubusercontent.com/94787812/222236515-7189f553-7c16-4920-8b8c-78b60bbd597c.png)

**Comment by vinicussresplandes** [comment]
![vini](https://user-images.githubusercontent.com/126600249/222235121-777ec150-c481-403a-a030-0fb80182a980.png),
Nome da equipe: Elite Ateniana
Componentes: Samila Esteves, Maria Eduarda Alencar e Vinicius Resplandes 
Passo a passo: Primeiro criamos a descrição da deusa Atena através do Chatgpt, em seguida traduzimos-a pelo Google tradutor, afim de utilizá-la no Midjourney onde a logo da equipe foi criada através da linguagem virtual.

**Comment by ju-santana** [comment]
Alunas: Ana Júlia Barros, Kamila Saraiva e Juliana Alves Santana 3A i

Em qua., 1 de mar. de 2023 às 14:55, Iury Gomes de Oliveira <
***@***.***> escreveu:

**Comment by iurygdeoliveira** [comment]
> https://docs.google.com/document/d/1kGLN4GcxIjv79A5NNXL3Z0nwSKSmfYM3obt6OLHDC7E/edit?usp=sharing
> 
> Nome da equipe: SLR
> 
> Integrantes: Samuel Teixeira, Luis Felipe e Rangerson Clemente
> 
> ![SLR](https://user-images.githubusercontent.com/126624010/222017767-e9366c92-f597-483f-90d0-dd809d1cc015.png)

corrigido

**Comment by iurygdeoliveira** [comment]
> https://docs.google.com/document/d/1Az-IqzUvO0jOzNaLMvrkD2JgmX12Gv3fGXwbrHHI5vM/edit
> 
> ![image](https://user-images.githubusercontent.com/126627347/222017875-1496a042-2bef-477d-8a04-70568bd1cba2.png)
> 
> Equipe: NetForce Integrante: José victor, Kezio

Sem acesso ao passo a passo, não há como corrigir. Liberar acesso para que eu possa fazer a correção

**Comment by iurygdeoliveira** [comment]
> EQUIPE **RESISTECH**
> 
> Lorenna Guedes e Simone Breeman
> 
> ![Resistech](https://user-images.githubusercontent.com/126627160/222018558-8060434a-3218-493c-93ea-08b7fa2981eb.jpg)
> 
> Descrição passo a passo, demonstrando o processo de criação realizado pela equipe: https://docs.google.com/document/d/1NcDo-8H4nczGi4Ov7-VnSTJHH4OjsE19ExFyh_N2C7U/edit?usp=sharing

Corrigido. Parabens, pela descrição, vocês executaram a tarefa com perfeição.

**Comment by iurygdeoliveira** [comment]
> Segue em anexo a imagem do grupo e o passo-a-passo de como foi feita [Relatório de desenvolvimento.docx](https://github.com/iurygdeoliveira/Web-development-classes/files/10856044/Relatorio.de.desenvolvimento.docx) ![cyber warriors](https://user-images.githubusercontent.com/108137566/222018706-9b596b2d-f6c8-4b64-a123-663b9e274441.png)

Corrigido

**Comment by iurygdeoliveira** [comment]
> Nome da equipe: Pro-Dog-IA
> 
> ![logogithub](https://user-images.githubusercontent.com/115494201/222018923-cde995be-ed73-4619-858a-4e67b5f1c478.jpg)
> 
> [Passo a passo .docx](https://github.com/iurygdeoliveira/Web-development-classes/files/10856058/Passo.a.passo.docx)

corrigido

**Comment by iurygdeoliveira** [comment]
> ![adielsoneeduarda](https://user-images.githubusercontent.com/126627177/222019054-f1ee3767-26b1-4c31-8777-52ed593e9c83.png)
> 
> https://docs.google.com/document/d/1h9zYzkcMs-q36K4T5Rf6jMBr66GpBW7XVzRgW0Mku5w/edit?usp=sharing

O acesso ao passo a passo está bloquado. Favor  tornar o acesso publico para que eu possa verificar

**Comment by iurygdeoliveira** [comment]
> Nome da Equipe: As Três Mosqueteiras
> 
> https://docs.google.com/document/d/1O2BK8z_8g7WbFWepONrbBWLZJFBDmXsYHNNe5E6KuQ8/edit?usp=sharing
> 
> ![Logomarca (1)](https://user-images.githubusercontent.com/126616901/222215476-d396faa6-d297-4782-97cb-e848757ee269.png)

corrigido

**Comment by iurygdeoliveira** [comment]
> GODDESSES OF CODING

corrigido

**Comment by iurygdeoliveira** [comment]
> 

corrigido

**Comment by gff001** [comment]
> 



> > NOME DA EQUIPE: G.A ![LOGO_FINAL](https://user-images.githubusercontent.com/126627187/222016341-f2afe36c-8d27-46b7-b0f8-f1de6d359a3a.jpg)
> 
> Onde está o passo a passo ? Onde está o nome dos integrantes da equipe ? Qual é a turma ?

LOGO REFEITA, NOME DOS INTEGRANTES GUILHERME E ALANNA, CURSO TADS, NOVO NOME DA EQUIPE ORCACA, OUTRAS INFORMAÇÕES DISPONÍVEL NO PDF ANEXADO JUNTO A NOVA LOGO

**Comment by kiaraalcantara** [comment]
Equipe: **The_Makers**
> 
> Integrantes: André Moreira, Kiara Alcântara, Natan Chiang
> 
> ![luadev - logo](https://user-images.githubusercontent.com/76929010/222319120-4fbc30d1-482e-425f-ae97-1cebe6bbd6fb.png)
> 
> Descrição, passo a passo da criação da nossa imagem. 
> [https://docs.google.com/document/d/1cFQ7yW1YhOWtGBfJaCR0mMSUkzYIasVUFt-a3H8SGOo/edit?usp=sharing](url)
>

**Comment by GustavoTvo** [comment]
https://docs.google.com/document/d/1n2CDqK2kRL1ie1Jo1--pR4ifYVvtVdDtX_7IE9IwoBQ/edit?usp=sharing

Integrante: Franklei Alves, Gustavo Tavares, Nicoly Farias 
Nome da equipe: Olhos do Futuro
![gustavohub_young_black_people_with_traces_of_electricity_and_te_0433d2b6-4c3f-416d-9994-a5ac54b0206b](https://user-images.githubusercontent.com/126599747/222602096-aea3c7e0-c380-4236-8f9c-5193b5a35bdc.png)

**Comment by yasmincosta21** [comment]
>

**Comment by yasmincosta21** [comment]
NOME DA EQUIPE: ABY (Iniciais dos nossos nomes);

DOCUMENTO COM O PASSO A PASSO:
https://docs.google.com/document/d/1T38A7jxN05zVvmJgznUnUuR_-W3wu1bT1iPMaknICsg/edit?usp=sharing

LOGOTIPO:
![final](https://user-images.githubusercontent.com/126615967/222216424-e1733bc0-cfef-4803-9bcc-6fe73cdb9cce.png)

**Comment by RenataGomes123** [comment]
Grupo:coded Ladies
https://docs.google.com/document/d/1uuMulbGnSdwWMcQS2lL6d8CjMz2AVoA9pX1M8a2vneY/edit?usp=sharing
![123](https://user-images.githubusercontent.com/126616099/222719857-c5f347b7-50d0-478f-83f0-2515dc9df7e7.png)

**Comment by brunnaborgex** [comment]
NOME DA EQUIPE: Autarquia
PASSO A PASSO: https://docs.google.com/document/d/1SegDBoD_NvEEVjz_BTKKp_6kFRZfS0AVBFHCTgXfASM/edit?usp=sharing 

![LOGO](https://user-images.githubusercontent.com/126615706/223179182-3af30f76-e429-45d3-b8f6-23bff357e2fc.png)

**Comment by huannyy** [comment]
IFTO - CAMPUS ARAGUAÍNA
Disciplina: Desenvolvimento Web
Professor: Iury Oliveira
Alunas: Huanny Barbosa, Izabela Queiroz e Camila Rodrigues
Turma: 3° A de informática
Nome da equipe: ELEKTRAS

https://docs.google.com/document/d/1WzQf1d-VWPRBDUlak48UFy6R7MG3Jp7InN1Un8koSZ0/edit?usp=sharing

obs: a imagem está na descrição
