### ISSUE TITLE
16º Desafio: Progresso passo a passo - Peso 1

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#20]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

E aí, crianças inocentes! Tudo bem por aí? Hoje eu tenho um desafio para vocês: desenvolver uma animação incrível utilizando HTML, CSS e JavaScript! Mas não é qualquer animação, é uma progresso passo a passo! Será que vocês estão prontos para esse desafio?

Primeiramente, vamos lembrar que a programação é como uma receita de bolo. Temos que seguir as instruções com cuidado para que o resultado final fique delicioso. Então, lembrem-se de prestar atenção aos detalhes e seguir as etapas do desafio.

Exemplo:
![CPT2303080859-350x104](https://user-images.githubusercontent.com/30157522/223709474-0dab40e8-385a-4a50-9dc2-21cf9ded90b2.gif)

A implementação dessa funcionalidade **NÃO** pode ser feita utilizando bibliotecas e frameworks já existentes, **APENAS** criando um código personalizado do zero. 

Lembrem-se de testar a animação em diferentes navegadores e dispositivos para garantir que tudo esteja funcionando perfeitamente. E não se esqueçam de se divertir e experimentar coisas novas durante o processo!

Eu sei que vocês são capazes de criar uma animação incrível de progresso passo a passo utilizando HTML, CSS e JavaScript. Então, vamos colocar a mão na massa e mostrar para o mundo do que somos capazes! Ah, e não se esqueçam de comer umas guloseimas pelo caminho!

### Additional tips

Em suma, a elaboração de um site com funcionalidade de progresso é um desafio interessante e enriquecedor para os alunos de programação, pois desenvolve habilidades de programação, além de permitir a criação de diferentes tipos de conteúdo para a web.

Outra dica para contrução do circulo e da barra de progresso é criar duas classes de css no seguinte estilo

```
.progress {
 // aqui ficará o código CSS responsável por controlar a barra de progresso.
 // Alguns comandos css podem ser úteis para ajudar na construção, por 
 // exemplo:   background-color, transform: translateY(-50%),  transition
}
```

```
.circle {
// aqui ficará o código CSS responsável por controlar a barra de progresso.
 // Alguns comandos css podem ser úteis para ajudar na construção, por 
 // exemplo:   background-color,  color, border-radius,  display: flex ,  justify-content: center;
 }
```

**Comment by huannyy** [comment]
[huanny.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10959936/huanny.zip)

**Comment by iurygdeoliveira** [comment]
> Equipe: Elektras [huanny.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10959936/huanny.zip)

Resposta aceita
