### ISSUE TITLE
17º Desafio: Rotação de animação de navegação - Peso 2

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#21]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Opa, meus alunos inocentes! Vamos lá, hoje eu trago um desafio quentinho para vocês. O desafio consiste em criar uma animação de navegação que vai deixar os usuários girando de alegria! Mas, calma lá, **nada de usar frameworks prontos**, vamos fazer isso do zero com HTML, CSS e JavaScript!

A ideia é criar uma animação de navegação em que os itens da lista sejam dispostos em círculo e girem quando o mouse for clicado. A navegação ter uma aparência limpa e moderna.

**Exemplo**
![animacao](https://user-images.githubusercontent.com/30157522/223711991-8ac48192-a1c2-48cc-9e6e-df7f7ae1bf46.gif)

Lembrando que a animação de navegação não é apenas para fazer algo bonito, mas também para melhorar a experiência do usuário e tornar a navegação mais intuitiva. 

Então, preparem-se para colocar as mãos na massa e criar uma animação de navegação incrível. Tenho certeza de que vocês vão arrasar nesse desafio!

### Additional tips

Ah, e uma dica importante: mantenham a simplicidade! Não se preocupem em adicionar muitos efeitos extravagantes ou transições complicadas. O objetivo aqui é criar uma animação de navegação funcional e estilosa.

**Comment by AndreAmario** [comment]
[Teste.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10934642/Teste.zip)

**Comment by AndreAmario** [comment]
[Teste.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10934648/Teste.zip)

Equipe: The_Makers

**Comment by AndreAmario** [comment]
[Teste.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10934667/Teste.zip)

Equipe: The_Makers

**Comment by RangersonTI** [comment]
https://github.com/RangersonTI/Linguagem_WEB/raw/main/Projetos/Animacao%20com%20Rotacao.zip

Nome do arquivo: Animação com rotação

Equipe: SLR
