### ISSUE TITLE
18º Desafio: Carregamento Desfocado - Peso 1

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#23]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Bem-vindos, crianças inocentes! O desafio que trago para vocês hoje é um tanto quanto... embaçado! A tarefa é criar um carregamento desfocado, que irá impressionar e deixar qualquer usuário de queixo caído!

Para cumprir essa missão, vocês precisarão utilizar HTML, CSS e JavaScript para criar uma animação de carregamento que comece com um fundo embaçado e vá se tornando mais nítido à medida que o carregamento é concluído. **Nada de usar frameworks prontos**, aqui a ideia é colocar a mão na massa e criar algo único e original!

Para começar, vocês podem utilizar filtros CSS, como o blur(), para embaçar o fundo. Depois, utilizando JavaScript, vocês podem definir um temporizador para controlar a animação e ir reduzindo gradualmente o valor do filtro até que ele seja completamente removido.

Lembrem-se de caprichar nos detalhes, como a escolha das cores e das fontes utilizadas. Utilizem a criatividade e surpreendam a todos com a beleza e fluidez do carregamento desfocado que vocês irão criar!

Boa sorte e divirtam-se!

**Exemplo**

https://user-images.githubusercontent.com/30157522/223716567-9ef0a51d-8d52-41dd-9286-9ad1874c894d.mp4

### Additional tips

Não hesitem em perguntar em caso de dúvida.

**Comment by AndreAmario** [comment]
[Desafio.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10924284/Desafio.zip)

Grupo: The_Makers
