### ISSUE TITLE
2º Desafio - Quais os tipos de licença de software

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#3]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Caros alunos,

Sejam bem-vindos a mais um desafio de informática, desta vez, vamos testar seus conhecimentos sobre licenças de software. Sabemos que a maioria de vocês já deve ter ouvido falar em licenças de software, mas será que vocês sabem explicar as principais diferenças entre elas?

Antes de começarmos, deixem-me lembrá-los de que, em geral, uma licença de software é um acordo entre o criador do software e o usuário final que define os termos e condições de uso do software. É importante compreender que as licenças de software têm a finalidade de proteger os direitos autorais e a propriedade intelectual do criador do software.

Agora, sem mais delongas, cito aquelas licenças de software, que, a meu ver, são as mais utilizadas no mercado.

-  Licença Proprietária 
-  Licença de Código Aberto 
-  Licença GPL 
-  Licença BSD 
-  Licença MIT 

**O desafio consiste em elaborar uma única redação-dissertativa contendo informações sobre todas as licenças, a redação deve ter no mínimo 120 linhas. 
Com a redação, os aluno deverá dizer quais as fontes utilizadas pela equipe para elaborar a redação, podem utilizar o campo de comentários para isso.
A redação deverá ser entregue em formato digital, em arquivo PDF, salve o arquivo na nuvem e poste o link nos comentários. Não se esqueça de incluir na redação a identificação da equipe, com o logotipo** 

E aí, estão prontos para esse desafio? Esperamos que sim! Não se esqueçam que é fundamental entender as diferenças entre as licenças de software antes de escolher a melhor opção para o seu projeto. Agora, mãos à obra!

### Additional tips

Depois de descobrirem sobre a existência de licenças de software. As licenças de software podem ser comparadas com os diferentes tipos de amizade que encontramos na sala de aula!

A **Licença Proprietária** seria como aquela amizade que você tem com aquele colega que só permite que você use sua caneta durante uma prova se você concordar em dar-lhe uma bala em troca depois. Já a **Licença de Código Aberto** seria como aquela amizade que você tem com o colega que compartilha todas as suas anotações com você e está sempre disposto a ajudá-lo a entender um conceito difícil. 

A **Licença GPL** seria como aquela amizade que é muito intensa e que exige que você e seu colega estejam sempre juntos em tudo o que fazem, como se fossem um único ser. A **Licença BSD** seria como aquela amizade que é aberta e flexível, permitindo que vocês tenham suas próprias vidas e interesses, mas ainda assim apoiando-se mutuamente quando necessário. Por fim, a **Licença MIT** seria como aquela amizade mais descontraída e descomplicada, onde você e seu colega podem seguir caminhos diferentes sem se preocupar em manter contato o tempo todo.

Espero que tenha ajudado vocês a entenderem melhor as diferentes licenças de software e a importância de escolher a amizade certa na sala de aula. Lembrando que sempre é bom ter uma mistura de todas essas licenças de amizade na vida para ter uma experiência completa e equilibrada!

**Comment by apauloenzo** [comment]
[Redação Licenças de Software (2).pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10855878/Redacao.Licencas.de.Software.2.pdf)

As fontes utilizadas foram:
Free Software Foundation. "GNU General Public License (GPL)." https://www.gnu.org/licenses/gpl-3.0.en.html

Open Source Initiative. "Open Source Licenses." https://opensource.org/licenses

Berkeley Software Distribution. "The BSD License." https://www.freebsd.org/copyright/license.html

Massachusetts Institute of Technology. "The MIT License." https://opensource.org/licenses/MIT

**Comment by rafaelnamel0** [comment]
<h1>Equipe ThreeCoders</h1>
[TIPOS DE LICENÇA DE SOFTWARE - DESAFIO 2.pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10863483/TIPOS.DE.LICENCA.DE.SOFTWARE.-.DESAFIO.2.pdf)

**BIBLIOGRAFIA:**
"OSI Approved Licenses" https://opensource.org/licenses/#:~:text=Open%20source%20licenses%20are%20licenses,Source%20Initiative%27s%20license%20review%20process
"Software de código aberto: o que é e quais suas vantagens." https://sambatech.com/blog/insights/codigo-aberto/
"Tipos de licença de software: tudo o que você precisa saber sobre eles" https://www.valuehost.com.br/blog/tipos-de-licenca-de-software/
"GNU General Public License" https://www.ufrgs.br/soft-livre-edu/wiki/GNU_General_Public_License
"Como funciona a licença BSD?"  https://definirtec.com/ampliar/23330/como-funciona-a-licenca-bsd
"Licenciamento de Software: o que é e como funciona?" https://www.uppertools.com.br/blog/licenciamento-de-software-o-que-e-e-como-funciona/

**Comment by edsonjrn** [comment]
[licenças de software.pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10863784/licencas.de.software.pdf)


<h1>Bibliografia:<\h1> 
"Open Source Initiative" - Site oficial da organização responsável por definir e promover o conceito de software livre e de código aberto: https://opensource.org/

"Free Software Foundation" - Site oficial da organização criada por Richard Stallman para promover a liberdade dos usuários de software: https://www.fsf.org/

"GNU General Public License" - Texto completo da licença GPL, uma das licenças de software livre mais utilizadas: https://www.gnu.org/licenses/gpl-3.0.en.html

"MIT License" - Texto completo da licença MIT, uma das licenças de software livre mais permissivas: https://opensource.org/licenses/MIT

"Apache License" - Texto completo da licença Apache, outra licença de software livre bastante utilizada: https://www.apache.org/licenses/LICENSE-2.0

**Comment by byancamamedes** [comment]
bibliografia: 
Tipos de Licença de Software - https://www.agtic.ufpr.br/pds-ufpr/ProcessoDemoisellePlugin/guidances/supportingmaterials/tiposLicencasSoftware_AD711F8B.html
GNU General Public License-https://www.ufrgs.br/soft-livre-edu/wiki/GNU_General_Public_License
Como funciona a licença BSD?- https://definirtec.com/ampliar/23330/como-funciona-a-licenca-bsd

[redação licenças de software-1.pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10864258/redacao.licencas.de.software-1.pdf)

**Comment by raykagomess** [comment]
[FIX - DESAFIO - 2 (1).pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10864559/FIX.-.DESAFIO.-.2.1.pdf)
**Bibliografia**
Licença Proprietaria - http://www2.decom.ufop.br/terralab/licencas-e-direitos-autorais-por-que-sao-importantes-para-os-projetos-de-software/#:~:text=As%20licen%C3%A7as%20propriet%C3%A1rias%20imp%C3%B5em%20condi%C3%A7%C3%B5es,%C3%A9%20um%20cerceamento%20de%20liberdade.

Licença de Código Aberto - https://blog.locaweb.com.br/temas/codigo-aberto/codigo-aberto-codigo-fechado/

Licença GPL - https://www.ufrgs.br/soft-livre-edu/wiki/GNU_General_Public_License#:~:text=Em%20termos%20gerais%2C%20a%20GPL,pr%C3%A9%2Drequisito%20para%20esta%20liberdade.

Licença BSD - https://definirtec.com/ampliar/23330/como-funciona-a-licenca-bsd

Licença MIT - https://www.uppertools.com.br/blog/licenciamento-de-software-o-que-e-e-como-funciona/

Conclusão - https://chat.openai.com/chat

**Comment by iurygdeoliveira** [comment]
> [Redação Licenças de Software (2).pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10855878/Redacao.Licencas.de.Software.2.pdf)
> 
> As fontes utilizadas foram: Free Software Foundation. "GNU General Public License (GPL)." https://www.gnu.org/licenses/gpl-3.0.en.html
> 
> Open Source Initiative. "Open Source Licenses." https://opensource.org/licenses
> 
> Berkeley Software Distribution. "The BSD License." https://www.freebsd.org/copyright/license.html
> 
> Massachusetts Institute of Technology. "The MIT License." https://opensource.org/licenses/MIT

O texto até apresenta uma introdução que apresenta o tema e os tipos de licenças de software que serão discutidos, desenvolvimento que apresenta informações sobre cada tipo de licença de software, características e exemplos de uso na comunidade de software livre e de código aberto e uma conclusão que resume os pontos apresentados na dissertação. 
Mas no entanto, faltou formatar o texto para ocupar o espaço, correto das folhas, dificil saber se atende 120 linhas.

**Comment by iurygdeoliveira** [comment]
> # Equipe ThreeCoders
> 
> [TIPOS DE LICENÇA DE SOFTWARE - DESAFIO 2 (ThreeCoders).pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10863548/TIPOS.DE.LICENCA.DE.SOFTWARE.-.DESAFIO.2.ThreeCoders.pdf)
> 
> **BIBLIOGRAFIA:** "OSI Approved Licenses" https://opensource.org/licenses/#:~:text=Open%20source%20licenses%20are%20licenses,Source%20Initiative%27s%20license%20review%20process "Software de código aberto: o que é e quais suas vantagens." https://sambatech.com/blog/insights/codigo-aberto/ "Tipos de licença de software: tudo o que você precisa saber sobre eles" https://www.valuehost.com.br/blog/tipos-de-licenca-de-software/ "GNU General Public License" https://www.ufrgs.br/soft-livre-edu/wiki/GNU_General_Public_License "Como funciona a licença BSD?" https://definirtec.com/ampliar/23330/como-funciona-a-licenca-bsd "Licenciamento de Software: o que é e como funciona?" https://www.uppertools.com.br/blog/licenciamento-de-software-o-que-e-e-como-funciona/

O texto apresentado atende aos requisitos de uma redação dissertativa para o Enem. O autor apresenta uma introdução ao tema, desenvolve uma discussão apresentando diferentes tipos de licenças de software e suas implicações, concluindo com a análise das licenças proprietária, de código aberto, GPL, BSD e MIT. Além disso, o autor também apresenta exemplos e argumentos para defender as suas posições e utiliza a norma culta da língua portuguesa. O texto possui uma boa formatação de texto
