### ISSUE TITLE
25º Desafio - Incremente Counter - Peso 1

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#30]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Olá, crianças inocentes! Vamos falar agora de um desafio super legal: criar um contador de inscritos para o canal do YouTube, outro para o Twitter e mais um para o facebook, tudo isso usando CSS, JS e HTML. E o melhor de tudo, sem usar frameworks prontos, hein?

Mas não se preocupem, que eu vou dar dicas valiosas para ajudar nessa empreitada. Para criar os contadores, vocês podem usar variáveis CSS para armazenar os valores e atualizá-los com JavaScript. Ah, e não se esqueçam de usar eventos para capturar as interações do usuário e atualizar os contadores em tempo real.

Lembrando sempre que o objetivo é aprender e se divertir, então não tenham medo de tentar coisas novas e experimentar diferentes abordagens para a solução do problema. Com um pouquinho de dedicação e criatividade, tenho certeza que vocês vão arrasar nesse desafio!

E lembrem-se: Vamos colocar a mão na massa e criar nossas próprias soluções incríveis!
**Exemplo:**

https://user-images.githubusercontent.com/30157522/224489503-bb675d5c-9465-4bb3-b407-728d30d4ec6d.mp4

### Additional tips

Dica de CSS: use display: flex para alinhar os elementos na tela e font-family para escolher a fonte dos números.

Dica de JS: use document.getElementById() para selecionar os elementos HTML dos contadores, e setInterval() para atualizar os valores a cada segundo.

Dica de ícones: utilizem a biblioteca font awesome, para gerar os ícones mais facilmente

**Comment by apauloenzo** [comment]
[desafio14.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10983374/desafio14.zip)
Equipe: Flasco

**Comment by apauloenzo** [comment]
[desafio25.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10983386/desafio25.zip)
Equipe: Flasco
