### ISSUE TITLE
30º Desafio - Drag N Drop - Peso 2

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#35]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Queridas crianças inocentes, tenho um desafio emocionante para vocês! Vamos criar juntos o efeito Drag N Drop, onde vocês poderão arrastar e soltar elementos na página.

Vamos lá, para começar, precisamos entender que o Drag N Drop é um recurso que permite a interação do usuário com a página. Para isso, precisamos utilizar HTML, CSS e JS.

No HTML, precisamos criar elementos que possam ser arrastados, como imagens ou caixas de texto. No CSS, podemos personalizar o estilo dos elementos e criar um feedback visual durante o processo de arrastar. Já no JS, precisamos definir o comportamento do elemento ao ser arrastado e solto, como sua posição na página.

Para criar esse efeito, vocês podem utilizar os eventos de mouse e touch do JS, como o evento "dragstart" para iniciar o arraste e o evento "drop" para soltar o elemento no local desejado.

Além disso, podemos utilizar comandos de CSS como "cursor: grab" para mudar o cursor do mouse ao segurar um elemento e "pointer-events: none" para desabilitar a interação com outros elementos durante o arraste.

Então, crianças inocentes, vamos colocar as mãos na massa e criar um efeito Drag N Drop incrível! Lembrem-se de praticar bastante e explorar diferentes opções de personalização e interação para deixar o projeto ainda mais divertido.

**Exemplo:**

https://user-images.githubusercontent.com/30157522/224492170-68ba4201-e262-43c3-a690-c6eb3080e163.mp4

### Additional tips

Código HTML

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <title>Drag N Drop</title>
  </head>
  <body>
    <div class="empty">
      <div class="fill" draggable="true"></div>
    </div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>

    <script src="script.js"></script>
  </body>
</html>

```

**Comment by NoNullDev** [comment]
# Equipe Vikings

## Resultado

![_C__Users_XNull_Desktop_Programa%C3%A7%C3%A3o_Desafios%20de%20Desenvolvimento%20Web_Desafio%2030_index html](https://user-images.githubusercontent.com/97764442/225325667-f8d57805-2194-4de6-93d6-eb5c3595b5fd.png)

## HTML
```
<!DOCTYPE html>
<html lang=pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <title>Drag N Drop</title>
  </head>
  <body>
    <div class="empty">
      <div class="fill" draggable="true"></div>
    </div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>
    <div class="empty"></div>

    <script src="script.js"></script>
  </body>
</html>
```

## CSS

```
body {
    background-color: rgb(255, 240, 109);
    height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    overflow: hidden;
}

.empty {
    background: white;
    height: 150px;
    width: 150px;
    margin: 10px;
    border: solid 3px black;
}

.fill {
    background-image: url('https://source.unsplash.com/random/150x150');
    height: 145px;
    width: 145px;
}

.hovered {
    background-color: rgb(133, 124, 47);
}
```

## JS

```
const empties = document.querySelectorAll(".empty");
const fill = document.querySelector(".fill");

fill.addEventListener("dragstart", dragStart);
fill.addEventListener("dragend", dragEnd);

for (const empty of empties) {
  empty.addEventListener("dragover", dragOver);
  empty.addEventListener("dragenter", dragEnter);
  empty.addEventListener("dragleave", dragLeave);
  empty.addEventListener("drop", dragDrop);
}

function dragOver(e) {
  e.preventDefault();
}

function dragEnter(e) {
  e.preventDefault();
  this.className += " hovered";
}

function dragLeave() {
  this.className = "empty";
}

function dragStart() {
  this.className += " hold";
  setTimeout(() => (this.className = "invisible"), 0);
}

function dragEnd() {
  this.className = "fill";
}

function dragDrop() {
  this.className = "empty";
  this.append(fill);
}
```

Referência: https://www.javascripttutorial.net/web-apis/javascript-drag-and-drop/
