### ISSUE TITLE
31º Desafio: Drawing App - Peso 3

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#36]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Olá crianças inocentes! Estão preparados para se tornarem verdadeiros artistas da programação? Hoje proponho criarmos um Drawing App, um site onde vocês poderão soltar a imaginação e desenhar o que quiserem!

Para isso, precisaremos usar HTML, CSS e JavaScript. E não se preocupem, pois darei algumas dicas para vocês se orientarem.

Primeiro, precisaremos criar a área de desenho. Vocês podem fazer isso com um elemento canvas do HTML, que permite desenhar gráficos e animações em 2D. Depois, precisaremos de botões para escolher o tamanho do pincel e a cor do pincel. Para isso, podemos usar elementos de input do HTML, como range e color.

Agora vem a parte mais legal: o JavaScript! Precisaremos de alguns eventos para detectar quando o usuário está desenhando na tela, como mousemove e mousedown. Com esses eventos, podemos criar uma função que desenha linhas na tela com base na posição do mouse. E, é claro, precisaremos de uma variável para armazenar a cor e o tamanho do pincel escolhido pelo usuário.

Para ajudar ainda mais, deixo aqui algumas dicas de possíveis comandos CSS e JS que podem ser úteis:

CSS: cursor: pointer; (para mudar o cursor do mouse quando estiver sobre a área de desenho), display: flex; (para criar um layout flexível com os botões de escolha de cor e tamanho do pincel), align-items: center; justify-content: center; (para centralizar os botões na tela).

JS: addEventListener('mousemove', functionName); (para adicionar um evento de mousemove que chama uma função), context.lineTo(x, y); (para desenhar uma linha na área de desenho), context.strokeStyle = color; (para definir a cor do pincel), context.lineWidth = size; (para definir o tamanho do pincel).

Vamos lá, crianças! Soltem a imaginação e criem o Drawing App mais incrível de todos!

**Exemplo**

https://user-images.githubusercontent.com/30157522/224492663-a81d6204-5cb8-4bf4-b808-5e8d50694ec0.mp4

### Additional tips

Código HTML

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <title>Drawing App</title>
  </head>
  <body>
    <canvas id="canvas" width="800" height="700"></canvas>
    <div class="toolbox">
      <button id="decrease">-</button>
      <span id="size">10</span>
      <button id="increase">+</button>
      <input type="color" id="color">
      <button id="clear">X</button>
    </div>

    <script src="script.js"></script>
  </body>
</html>
```

**Comment by apauloenzo** [comment]
[drawingapp.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10979610/drawingapp.zip)
Equipe: Flasco
