### ISSUE TITLE
43º Desafio: Construindo um testimonial box - Peso 1

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#48]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Oi, crianças inocentes! O desafio de programação de hoje é construir um Testimonial Box! Isso mesmo, um site que vai mostrar aos visitantes o quão incrível é o seu site através dos depoimentos de usuários satisfeitos. Mas não se enganem, isso não é apenas uma questão de vaidade! Os Testimonials são uma técnica importante de marketing, pois eles ajudam a aumentar a confiança do visitante em seu site e consequentemente aumentam as chances de conversão em vendas ou outros objetivos que você tenha para o seu site.

Agora, quanto ao desafio, vocês terão que utilizar as linguagens de HTML, CSS e JS para construir o site que vai exibir os depoimentos dos usuários. Os depoimentos devem ser bem organizados e apresentados de forma clara e atrativa. Lembrem-se de que vocês não podem utilizar soluções prontas! É importante que vocês desenvolvam suas próprias soluções para que possam aprender e praticar suas habilidades.

Algumas dicas para ajudar vocês em seu desafio:

- Use o HTML para estruturar o conteúdo do site, como o título, subtítulo, o campo para o depoimento, o nome do usuário e outros elementos que você julgar necessários.
- Utilize o CSS para dar estilo ao site e torná-lo visualmente atraente. Isso pode incluir a escolha de fontes, cores e estilos de botões e outros elementos do site.
- Use o JavaScript para tornar o site interativo e para permitir que os usuários possam enviar seus depoimentos. Além disso, você pode usar o JavaScript para animar o site e dar a ele uma aparência mais dinâmica.

Com essas dicas, espero que vocês sejam capazes de construir um Testimonial Box incrível! Boa sorte, e não esqueçam de se divertir durante o processo de desenvolvimento. Vocês são incríveis!

**Exemplo**

https://user-images.githubusercontent.com/30157522/224550581-afac3737-f3db-4143-abea-0a1e6049e188.mp4

### Additional tips

Código HTML

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
      integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="style.css" />
    <title>Testimonial Box</title>
  </head>
  <body>
    <div class="testimonial-container">
      <div class="progress-bar"></div>
      <div class="fas fa-quote-right fa-quote"></div>
      <div class="fas fa-quote-left fa-quote"></div>
      <p class="testimonial">
        I've worked with literally hundreds of HTML/CSS developers and I have to
        say the top spot goes to this guy. This guy is an amazing developer. He
        stresses on good, clean code and pays heed to the details. I love
        developers who respect each and every aspect of a throughly thought out
        design and do their best to put it in code. He goes over and beyond and
        transforms ART into PIXELS - without a glitch, every time.
      </p>
      <div class="user">
        <img
          src="https://randomuser.me/api/portraits/women/46.jpg"
          alt="user"
          class="user-image"
        />
        <div class="user-details">
          <h4 class="username">Miyah Myles</h4>
          <p class="role">Marketing</p>
        </div>
      </div>
    </div>
    <script src="script.js"></script>
  </body>
</html>
```

**Comment by apauloenzo** [comment]
[desafio.zip](https://github.com/iurygdeoliveira/Web-development-classes/files/10974607/desafio.zip)
Equipe: Flasco
