### ISSUE TITLE
4º Desafio: Construção Automática de Apresentações 

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#5]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Caros alunos,

Quero desafiá-los a construir um vídeo que demonstre a utilização da ferramenta MagicSlides App GPT for Slides, disponível no Google Workspace Marketplace. [Link:](https://workspace.google.com/marketplace/app/magicslides_app_gpt_for_slides/371894645570)

Essa ferramenta, baseada na tecnologia de Processamento de Linguagem Natural (PLN), permite que o usuário crie apresentações de slides em segundos, a partir de texto escrito. O MagicSlides App GPT for Slides utiliza o GPT (Generative Pre-trained Transformer) para gerar automaticamente uma apresentação de slides a partir do conteúdo textual inserido pelo usuário, que pode ser editada e personalizada conforme as necessidades do apresentador.

O objetivo desse desafio é que vocês criem um vídeo que demonstre a utilização da ferramenta MagicSlides App GPT for Slides de forma clara e objetiva, destacando as suas principais funcionalidades e vantagens em relação a outras ferramentas de criação de apresentações de slides.

Para cumprir esse desafio, vocês devem seguir os seguintes passos:

1.     Acessar o link do MagicSlides App GPT for Slides na Google Workspace Marketplace;
2.     Instalar a ferramenta em sua conta do Google Workspace;
3.     Criar um texto de exemplo, com cerca de 2 a 3 parágrafos, que possa ser utilizado para a criação de uma apresentação de slides no MagicSlides App GPT for Slides;
4.     Utilizar a ferramenta para gerar uma apresentação de slides a partir do texto criado no passo anterior;
5.     Editar e personalizar a apresentação de slides gerada de acordo com as suas preferências e necessidades;
6.     Gravar um vídeo, com duração máxima de 5 minutos, demonstrando a utilização da ferramenta MagicSlides App GPT for Slides e destacando as suas principais funcionalidades e vantagens. O vídeo deve ser claro e objetivo, com uma narração clara e concisa, além de imagens ilustrativas da ferramenta em uso.

Ao finalizar o vídeo, vocês devem postar o link do vídeo para a minha avaliação, juntamente com o texto utilizado na criação da apresentação de slides e um breve relatório sobre a sua experiência com a ferramenta, destacando as suas impressões sobre a facilidade de uso, eficácia e usabilidade.

Espero que esse desafio seja uma oportunidade para que vocês aprimorem suas habilidades na criação de apresentações de slides, utilizando uma ferramenta inovadora e de alta tecnologia como o MagicSlides App GPT for Slides. Desejo a todos uma boa sorte e aguardo ansioso pelos seus vídeos!

### Additional tips

Vamos ser sinceros, o mercado de trabalho é como aquele chefe carrancudo que sempre espera que você faça uma apresentação de ideias impressionante. Mas não se preocupe, com o MagicSlides App GPT for Slides, você pode impressionar até mesmo o chefe mais durão!

Então, da próxima vez que você precisar apresentar suas ideias para um chefe carrancudo, não se preocupe! Com o MagicSlides, você pode transformar sua apresentação em uma tarefa muito mais fácil.

**Comment by apauloenzo** [comment]
https://screenrec.com/share/T9AnBcUgZ0
[Relatório.pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10889444/Relatorio.pdf)
[Texto utilizado. (1).pdf](https://github.com/iurygdeoliveira/Web-development-classes/files/10889445/Texto.utilizado.1.pdf)

Equipe: Flasco

**Comment by iurygdeoliveira** [comment]
Parabéns, você conclui com sucesso esse desafio, ponto pra equipe
