### ISSUE TITLE
Desafio 46º: Desenvolvimento de uma formulário de recrutamento e pessoal 

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#52]
### Contact Details

iurygdeoliveira@gmail.com

### Challenge Description

Olá, pequenos gênios da programação! Estamos felizes em tê-los conosco nesta aventura emocionante e desafiadora. É hora de mostrar suas habilidades mágicas em HTML, CSS e JavaScript! 🌟

Desafio: Crie um incrível e funcional "Formulário de Recrutamento" que ajudará uma empresa fictícia a encontrar os melhores talentos. Lembre-se, vocês são os artistas que darão vida a este formulário!

Instruções para o desafio:

1.  Use HTML para estruturar o formulário, criando campos de entrada e rótulos para todas as informações solicitadas no exemplo de formulário fornecido.
2.  Vista seu formulário com CSS, tornando-o visualmente atraente e fácil de navegar. Use cores, fontes e estilos que transmitam um ambiente profissional e amigável.
4.  Adicione um toque de magia com JavaScript! Crie validações para garantir que todos os campos obrigatórios sejam preenchidos e que os dados inseridos sejam válidos. Por exemplo, verifique se o e-mail possui o formato correto e se a data de nascimento não está no futuro. 
5.  Por último, mas não menos importante, inclua um botão de envio que colete todas as informações e as exiba de maneira organizada, como um resumo das respostas.
6. Os campos do formulário devem ser validados, ou seja, campos númericos só podem aceitar valores númericos na digitação, campos que podem valores de texto, só podem aceitar digitação de textos. Essa validação pode ser feita utilizando-se bibliotecas prontas de javascript (Ex.: [Exemplo de lib](https://jqueryvalidation.org/))
7. Utilizar as cores e logo do IFTO.

Lembre-se, crianças inocentes, este é um desafio para testar suas habilidades, criatividade e capacidade de resolver problemas. Vocês têm o poder de transformar este formulário em algo verdadeiramente mágico! 🧙

Agora, preparem-se, é hora de embarcar nesta jornada encantadora e criar o formulário de recrutamento mais fantástico que o mundo já viu. Boa sorte, e que a força da programação esteja com vocês! 🚀

Precisando de informações extras para construção de formulários ?
Acesse: https://web.dev/learn/forms/

**Vocês deverão postar o nome da equipe, seus ilustres integrantes e um link para o site com a proposta de vocês, utilizando o recurso do github.io para armazenar o site de vocês como um baú do tesouro.
Link com instruções: https://docs.github.com/pt/pages/getting-started-with-github-pages/creating-a-github-pages-site**

### Additional tips

Dados que devem estar neste formulário

```
Formulário de Recrutamento
As informações fornecidas neste formulário serão usadas exclusivamente para fins de recrutamento e seleção. Todos os campos são obrigatórios, exceto onde indicado o contrário.

**Dados Pessoais**

    1. Nome Completo:
    2. Data de Nascimento:
    3. Gênero:
    4. Nacionalidade:
    5. Endereço:
    7. Cidade:
    8. Estado:
    9. CEP:
    10. Telefone:
    
**Formação Acadêmica**

> Técnico em Informática
> Técnologo em Análise e Desenvolvimento de Sistemas

**Além da formação técnicas profissional ofertada no IFTO, já possui algum outro tipo de curso ? Se sim, qual ?**

**Experiências Profissionais**

> Não possuo

> Última ou Atual Empresa:
> Cargo:
> Período de Atuação (Mês/Ano – Mês/Ano):
> Principais Atividades e Responsabilidades:

**Se você possui mais experiências profissionais, liste-as abaixo (opcional):**

**Experiências Adicionais (Empresa, Cargo, Período, Atividades e Responsabilidades):**

**Habilidades Técnicas e Idiomas**

**Informe quais Habilidades Técnicas Relevantes (softwares, ferramentas, certificações):**
Possui habilidades com idiomas ? Qual Língua:
Nível de Proficiência (Básico, Intermediário, Avançado, Fluente)

**Habilidades Comportamentais**
Liste três habilidades comportamentais que você considera serem suas principais qualidades profissionais:

**Informações Adicionais**
Pretensão Salarial:
Disponibilidade para Início:
```

**Comment by EduardoSilva09** [comment]
## Equipe:  NetForce

### Nomes:  Eduardo, José, Kézio
### Endereço:  https://eduardosilva09.github.io/desafios-lp1/

**Comment by NoNullDev** [comment]
# Equipe Vikings

Alunos: Giorge Lucas, Filipe Carvalho, João Edson

> Link para o site: https://nonulldev.github.io/Site-empresa-ficticia/
> Link para o repositório: https://github.com/NoNullDev/Site-empresa-ficticia

**Comment by rafaelnamel0** [comment]
<h1>Equipe ThreeCoders</h1>

<b>Resultado Final:</b> http://rafaelnamel0.github.io/desafio46/

Código: https://github.com/rafaelnamel0/desafio46

**Comment by samuelsamnx** [comment]
> ## Equipe: NetForce
> ### Nomes: Eduardo, José, Kézio
> ### Endereço: https://eduardosilva09.github.io/desafios-lp1/
Show papai

**Comment by kiaraalcantara** [comment]
# The Makers

Link do formulário: https://kiaraalcantara.github.io/Recrutamento/
3 erros

**Comment by Ghenry-san** [comment]
Fênix

Link do formulário: https://ghenry-san.github.io/Formul-rio-Web/

Link do repositório: https://github.com/Ghenry-san/Formul-rio-Web

**Comment by kauanynha05** [comment]
<h1>As Três Mosqueteiras </h1>

Link do site:

 https://kauanynha05.github.io/tresmosqueteiras/ 

link do repositorio: 

https://github.com/kauanynha05/tresmosqueteiras

**Comment by brunnaborgex** [comment]
EQUIPE : Autarquia
Link do site: https://brunnaborgex.github.io/Equipe-Autarquia/
Link do repositório: https://github.com/brunnaborgex/Equipe-Autarquia

**Comment by anbia1805carvalho** [comment]
3 errinhos

EQUIPE : ABY
Link do site: https://anbia1805carvalho.github.io/formulario/
Link do repositório: https://github.com/anbia1805carvalho/formulario

**Comment by Izabelaqueirox** [comment]
1 erro

Link do site: https://izabelaqueirox.github.io/formulario/ 
Link do repositório: https://github.com/Izabelaqueirox/formulario

**Comment by ItaloNishikawa** [comment]
1 erro

Equipe: PDF
Link do site: https://italonishikawa.github.io/form-emprego/index.html
link do repositório: https://github.com/ItaloNishikawa/form-emprego

**Comment by WandesonG0101** [comment]
Equipe: Saiyajins
link do site: https://wandesong0101.github.io/reposit/
link repositório: https://github.com/WandesonG0101/reposit

**Comment by RangersonTI** [comment]
`<h1>Equipe SLR</h1>`

Link para o formulário: https://rangersonti.github.io/Formulario-IF/
Integrantes: Luis Felipe, Samuel Teixeira e Rangerson Clemente

**Comment by Alanna-Gamaa** [comment]
### DUO ORCACA

**ALUNOS: ALANNA, GUILHERME**

link do site: https://alanna-gamaa.github.io/index.html
link repositório: https://github.com/Alanna-Gamaa/Alanna-Gamaa.github.io

**Comment by Andre-Neres** [comment]
**Equipe CyberWorriors**
Carlos Andre Neres da Silva
Alysson Neres da Silva
Thobias Batista Costa Silva

Links:

https://github.com/Andre-Neres/projetosandre
https://andre-neres.github.io/projetosandre/

**Comment by lor3nna** [comment]
**Equipe RESISTECH**
Lorenna Guedes
Simone Breeman

Links:
https://simonebreeman.github.io/Desafio-46/
https://github.com/simonebreeman/Desafio-46

**Comment by Monalisa-Gama** [comment]
**Equipe Phytomancers**
Monalisa Gama
Albert Soares

Links:
https://github.com/Monalisa-Gama/form
https://monalisa-gama.github.io/form/

**Comment by Analicemc** [comment]
## Equipe Lovelace
Repositório: [https://github.com/Analicemc/desafio-46](url)
Site: [https://analicemc.github.io/desafio-46/](url)

**Comment by AnaRaquel28** [comment]
### Equipe Alpha

Repositório: [https://github.com/AnaRaquel28/teste](https://github.com/AnaRaquel28/teste)
formulario: [https://anaraquel28.github.io/teste/](https://anaraquel28.github.io/teste/)

**Comment by iurygdeoliveira** [comment]
> ## Equipe: NetForce
> ### Nomes: Eduardo, José, Kézio
> ### Endereço: https://eduardosilva09.github.io/desafios-lp1/

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :+1:
Utilização de Javascript para aplicar dinamismo: :+1:

Avaliação:
5 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> 
> # Equipe Vikings
> Alunos: Giorge Lucas, Filipe Carvalho, João Edson
> 
> > Link para o site: https://nonulldev.github.io/Site-empresa-ficticia/
> > Link para o repositório: https://github.com/NoNullDev/Site-empresa-ficticia

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :-1:
Na aparência geral e na funcionalidade do novo layout: :-1:
Implementações extras, avanços além daquilo pedido pelo professor: :+1:
Utilização de Javascript para aplicar validação nos campos: :+1:

Avaliação:
3 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> # Equipe ThreeCoders
> Resultado Final: http://rafaelnamel0.github.io/desafio46/
> 
> Código: https://github.com/rafaelnamel0/desafio46

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :+1:
Utilização de Javascript para aplicar validação nos campos: :+1:

Avaliação:
5 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> # The Makers
> Link do formulário: https://kiaraalcantara.github.io/Recrutamento/
> 
> Link do repositório: https://github.com/kiaraalcantara/Recrutamento
> 
> 3 erros

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :-1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
3 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> Fênix
> 
> Link do formulário: https://ghenry-san.github.io/Formul-rio-Web/
> 
> Link do repositório: https://github.com/Ghenry-san/Formul-rio-Web
> 
> 3 erros

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :-1:
Na aparência geral e na funcionalidade do novo layout: :-1:
Implementações extras, avanços além daquilo pedido pelo professor: :+1:
Utilização de Javascript para aplicar validação nos campos: :+1:

Avaliação:
3 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> 6 erros
> 
> # As Três Mosqueteiras
> Link do site:
> 
> https://kauanynha05.github.io/tresmosqueteiras/
> 
> link do repositorio:
> 
> https://github.com/kauanynha05/tresmosqueteiras

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :-1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :-1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
2 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> 1 erro
> 
> EQUIPE : Autarquia Link do site: https://brunnaborgex.github.io/Equipe-Autarquia/ Link do repositório: https://github.com/brunnaborgex/Equipe-Autarquia

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :-1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
3 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> 3 errinhos
> 
> EQUIPE : ABY Link do site: https://anbia1805carvalho.github.io/formulario/ Link do repositório: https://github.com/anbia1805carvalho/formulario

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :-1:
Implementações extras, avanços além daquilo pedido pelo professor: :-1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
2 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> 1 erro
> 
> EQUIPE: ELEKTRAS Link do site: https://izabelaqueirox.github.io/formulario/ Link do repositório: https://github.com/Izabelaqueirox/formulario

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :+1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
4 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> 1 erro
> 
> Equipe: PDF Link do site: https://italonishikawa.github.io/form-emprego/index.html link do repositório: https://github.com/ItaloNishikawa/form-emprego

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :+1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
4 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> Equipe: Saiyajins link do site: https://wandesong0101.github.io/reposit/ link repositório: https://github.com/WandesonG0101/reposit
> 
> Alunos: Alisson Filepe de Aquino Santos, Eduardo Barbosa, Wanderson Gomes

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :-1:
Na organização e na clareza do código: :-1:
Na aparência geral e na funcionalidade do novo layout: :-1:
Implementações extras, avanços além daquilo pedido pelo professor: :-1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
0 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> **Equipe SLR**
> 
> Link para o formulário: https://rangersonti.github.io/Formulario-IF/ Link para o repositorio: https://github.com/RangersonTI/Formulario-IF
> 
> Integrantes: Luis Felipe, Samuel Teixeira e Rangerson Clemente

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :-1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
3 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> **Equipe Phytomancers** Monalisa Gama Albert Soares
> 
> Links: https://github.com/Monalisa-Gama/form https://monalisa-gama.github.io/form/

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :-1:
Implementações extras, avanços além daquilo pedido pelo professor: :-1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
2 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> ## Equipe Lovelace
> Repositório: [https://github.com/Analicemc/desafio-46](url) Site: [https://analicemc.github.io/desafio-46/](url)

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :-1:
Na aparência geral e na funcionalidade do novo layout: :+1:
Implementações extras, avanços além daquilo pedido pelo professor: :+1:
Utilização de Javascript para aplicar validação nos campos: :+1:

Avaliação:
4 de pontos para o ranking

**Comment by iurygdeoliveira** [comment]
> ### Equipe Alpha
> Integrantes: Ana Raquel; Byanca Mamedes e Pedro Henrique.
> 
> Repositório: https://github.com/AnaRaquel28/teste formulario: https://anaraquel28.github.io/teste/

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1:
Na organização e na clareza do código: :+1:
Na aparência geral e na funcionalidade do novo layout: :-1:
Implementações extras, avanços além daquilo pedido pelo professor: :+1:
Utilização de Javascript para aplicar validação nos campos: :-1:

Avaliação:
3 de pontos para o ranking
