### ISSUE TITLE
Desafio 47º: Hora de começar com Javascript

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#53]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Ei, jovens aprendizes do mundo da programação! ✨

Abrace seus poderes mágicos e preparem-se para uma aventura espetacular no reino encantado do JavaScript! Vocês foram convocados para dar vida e alegria à nossa amiguinha, a Tabela de Rankings de equipes, que se encontra solitária e estática neste link: https://iurygdeoliveira.github.io/Web-development-classes/ranking_equipes/index.html. Estão prontos para encarar esse desafio místico? Então, vamos nessa! 🌈

  1. Ordenação das linhas da tabela:
Adicione a funcionalidade de ordenar a tabela por qualquer coluna (Ranking, Equipe, Pontos, etc.). Para isso, crie uma função em JavaScript que detecte o clique no cabeçalho da tabela e ordene as linhas de acordo com o valor da coluna selecionada. Alterne entre ordem crescente e decrescente a cada clique.

2. Filtragem de equipes:
Crie uma barra de pesquisa acima da tabela para permitir que os usuários filtrem as equipes pelo nome. Utilize JavaScript para criar uma função que detecte a entrada do usuário no campo de pesquisa e filtre as linhas da tabela para exibir apenas aquelas que correspondem ao texto inserido. Restaure a tabela original quando o campo de pesquisa estiver vazio.

Lembrem-se, crianças inocentes, este é um desafio para testar seus poderes mágicos, criatividade e habilidades para solucionar enigmas. Vocês têm a capacidade de transformar essa tabela em algo verdadeiramente fantástico! 🌟

Após concluírem a missão, compartilhem conosco o nome da equipe, seus valentes integrantes e um link para o trabalho de vocês. Utilizem o recurso do github.io como para publicar o site da sua equipe.
Instruções: https://docs.github.com/pt/pages/getting-started-with-github-pages/creating-a-github-pages-site

### Additional tips

Precisando de fundamentos em javascript ?
Material complementar:[Slides]( https://docs.google.com/presentation/d/1gjEoocT0ZuoAlJKbcrFV6y1rZ-WvLQcjxFmDfdUeD4Y/edit#slide=id.g3ea4d772f5_0_0)
Acesse o link abaixo: https://www.youtube.com/watch?v=l1-OzK1CWh4&list=PLXik_5Br-zO-bZ7q3TC1oFbqwLP2491Ms

**Comment by EduardoSilva09** [comment]
# Equipe:  NetForce
#### Nomes: Eduardo, José, Kézio
#### Endereço: https://eduardosilva09.github.io/desafio-47-sort-table/

**Comment by NoNullDev** [comment]
# Equipe Vikings

Nomes: Giorge Lucas, Filipe Carvalho, João Edson

Link para o site: https://nonulldev.github.io/Ranking-Table-Sort/
Link para o repositório: https://github.com/NoNullDev/Ranking-Table-Sort

**Comment by Alanna-Gamaa** [comment]
### DUO ORCACA

**ALUNOS GUILHERME, ALANNA**

SITE: https://alanna-gamaa.github.io/index.html
REPOSITÓRIO: https://github.com/Alanna-Gamaa/Alanna-Gamaa.github.io

**OBS:** CLICAR NOS TH PARA ORDENAR

**Comment by iurygdeoliveira** [comment]
> # Equipe: NetForce
> #### Nomes: Eduardo, José, Kézio
> #### Endereço: https://eduardosilva09.github.io/desafio-47-sort-table/

Os critérios utilizados na avaliação:

Na aplicação da sintaxe básica do CSS: :+1: 
Na organização e na clareza do código: :+1: 
Na aparência geral e na funcionalidade do novo layout: :+1: 
Implementações extras, avanços além daquilo pedido pelo professor: :+1: 
Utilização de Javascript para aplicar dinamismo :+1: 

Avaliação:
5 de pontos para o ranking

**Comment by rafaelnamel0** [comment]
<h1>Equipe ThreeCoders</h1>

<b>Link para o site: </b>https://rafaelnamel0.github.io/rankingequipes/

Link para o repositório: https://github.com/rafaelnamel0/rankingequipes

**Comment by Edubssousa** [comment]
**### Equipe Saiyajins**
**Alunos: Eduardo Barbosa, Alisson Filipe e Wanderson Gomes**

Link do Site: https://edubssousa.github.io/eduardo.github/
Link do Repositório: **https://github.com/Edubssousa/eduardo.github**

**Comment by iurygdeoliveira** [comment]
> ## Equipe Lovelace - Analice e @suzanasantoss
> Link repositório: https://github.com/Analicemc/Ranking-de-equipes
> Link Site: https://analicemc.github.io/Ranking-de-equipes/
> 

Os critérios utilizados na avaliação:

Na organização e na clareza do código: 👍
Implementações extras 👍
Utilização de Javascript👍

Avaliação:
3 de pontos para o ranking

**Comment by alinelima28** [comment]
Equipe Autarquia
Nomes: Aline Lima e Brunna Borges
Link para o site: https://alinelima28.github.io/desafio47/
Link para o repositório: https://github.com/alinelima28/desafio47

**Comment by iurygdeoliveira** [comment]
> Equipe Autarquia
> Nomes: Aline Lima e Brunna Borges
> Link para o site: https://alinelima28.github.io/desafio47/
> Link para o repositório: https://github.com/alinelima28/desafio47 

Os critérios utilizados na avaliação:

Na organização e na clareza do código: 👍
Implementações extras 👍
Utilização de Javascript👍

Avaliação:
3 de pontos para o ranking

**Comment by ItaloNishikawa** [comment]
Equipe Pastel de Flango
Nomes: Italo Nishikawa, Edson Jr, Gustavo Frederico

Link para o site: https://italonishikawa.github.io/javascript_sort/
Link para o repositório: https://github.com/ItaloNishikawa/javascript_sort.git

**Comment by iurygdeoliveira** [comment]
> Equipe Pastel de Flango
> Nomes: Italo Nishikawa, Edson Jr, Gustavo Frederico
> 
> Link para o site: https://italonishikawa.github.io/javascript_sort/
> Link para o repositório: https://github.com/ItaloNishikawa/javascript_sort.git

Os critérios utilizados na avaliação:

Na organização e na clareza do código: 👍
Implementações extras :-1:
Utilização de Javascript :-1:

Avaliação:
1 de pontos para o ranking

**Comment by GLMarco** [comment]
EQUIPE FIX - Marcos, Rayka e Rita
REPÓSITORIO - https://github.com/GLMarco/glmarco.github.io.git
SITE - https://glmarco.github.io/
(Não consegui corrigir o problema da barra de pesquisa)

**Comment by apauloenzo** [comment]
Arquivos: https://github.com/apauloenzo/ordena-o-de-coluna.git

**Comment by Ghenry-san** [comment]
EQUIPE: Fênix

Link : https://github.com/Ghenry-san/Desafio47

**Comment by simonebreeman** [comment]
EQUIPE: RESISTECH
Alunas: Lorenna Guedes e Simone Breeman

Site: https://lor3nna.github.io/desafio47/
Repositório: https://github.com/lor3nna/desafio47.git

**Comment by AnaRaquel28** [comment]
###Equipe: ALFA ### 
Integrantes: Ana Raquel; Byanca Mamedes e Pedro Henrique.

Link Site: [https://anaraquel28.github.io/Desafio47/](https://anaraquel28.github.io/Desafio47/)
Link Repositório: [https://github.com/AnaRaquel28/Desafio47](https://github.com/AnaRaquel28/Desafio47)

**Comment by Monalisa-Gama** [comment]
Equipe: Phytomancers
Alunos: Monalisa Cabral, Albert Soares

Link site: https://monalisa-gama.github.io/Desafio-47/
Link Repositório: https://github.com/Monalisa-Gama/Desafio-47
