### ISSUE TITLE
6º Desafio: Como contribuir com outros projetos no github - Peso 1

### ISSUE THREAD

**Issue by iurygdeoliveira** [iurygdeoliveira/Web-development-classes#7]
### Contact Details

iury.oliveira@ifto.edu.br

### Challenge Description

Olá alunos,

Neste desafio, você deve contribuir para o repositório iurygdeoliveira/Web-development-classes. O objetivo é que você aprenda a como utilizar o Github para contribuir com um projeto de código aberto e aprender a enviar um Pull Request (PR).

O Github é uma plataforma essencial para o trabalho de um desenvolvedor. Ele oferece uma maneira fácil de colaborar com outras pessoas em projetos de código aberto e de controlar versões de código. Além disso, é uma ferramenta valiosa para construir um portfólio de projetos e para se envolver com a comunidade de desenvolvedores.

O uso do Github pode ajudá-lo a melhorar suas habilidades de colaboração e a aprender com os outros. Ao contribuir para projetos de código aberto, você pode obter feedback sobre seu código e se envolver em discussões com outros desenvolvedores. Isso pode ajudá-lo a melhorar suas habilidades de programação e a se tornar um desenvolvedor mais experiente.

Contribuir para um projeto de código aberto pode parecer intimidador no início, mas é uma maneira valiosa de melhorar suas habilidades de programação e construir seu portfólio. O desafio de Pull Request no Github descrito acima é uma maneira fácil de começar a contribuir para projetos de código aberto e deaprender como enviar um PR usando o Github. É importante lembrar que, ao contribuir para um projeto de código aberto, você deve seguir as diretrizes do projeto e trabalhar em colaboração com outros contribuintes.

O repositório iurygdeoliveira/Web-development-classes é um ótimo lugar para começar a contribuir para um projeto de código aberto. O repositório é focado em ensinar conceitos de programação web para iniciantes.

Para contribuir para o repositório "Web-development-classes" por meio do Git e do GitHub, siga os seguintes passos:

1. Faça um fork do repositório web-development-classes"

Acesse a página do repositório "Web-development-classes" e clique no botão "Fork" no canto superior direito. Isso criará uma cópia do repositório na sua conta do GitHub.

 2. Clone o repositório para o seu computador, para incluir e alterar o código com mais facilidade.

Na linha de comandos do computador (terminal), digite o comando git clone seguido da URL do repositório forkado. Isso fará o download do repositório para a sua máquina local.

git clone https://github.com/seu-usuario-do-github/Web-development-classes.git

O comando acima vai gerar uma pasta chamada Web-development-classes no seu computador, contendo o código do repositório.

3. Crie um branch para a sua contribuição

cd Web-development-classes (Para acessar a pasta criada contendo o código do repositorio)
git checkout -b titulo-da-sua-contribuição

4. Faça as alterações ou inclusões no código

5. Digite o comando git add seguido dos arquivos que você alterou ou do ponto . para adicionar todas as alterações.

git add .

6. Faça o commit das alterações. Digite o comando git commit seguido de uma mensagem de commit que descreva as alterações que você fez.

git commit -m "comentario que explica suscintamente suas alterações"

7. Envie as alterações para o GitHub .Digite o comando git push para enviar as suas alterações para o seu repositório forkado.

git push origin titulo-da-sua-contribuição

8. Crie um Pull Request

Volte para a página do repositório original no GitHub e clique no botão "New pull request". Isso abrirá uma nova página onde você poderá revisar as alterações que fez e criar um pull request. Certifique-se de selecionar o branch correto que contém as suas alterações.

Agora é só esperar que alguém do repositório original aprove sua contribuição!

### Additional tips

Opa, vamos às dicas no desafio de Pull Request no Github!

1. Comece pelo básico: Se você é novo no Github e não tem ideia de como contribuir em projetos através de um Pull Request, não se preocupe! Existem muitos tutoriais incríveis por aí que podem te ajudar. O Google e o ChatGPT são seus amigos, basta pesquisar "Como enviar um Pull Request no Github" e começar a estudar.
2. Não seja tímido: Contribuir para um projeto de código aberto pode parecer dificil no começo, mas lembre-se de que você está em um ambiente de aprendizado e de colaboração. Não tenha medo de fazer perguntas e pedir ajuda se precisar, o professor é seu amigo.
3. Observe o código já feito, e escolha uma parte que você tenha mais facilidade: Você pode se sentir mais confortável contribuindo com uma parte do código que que você já conhece e gosta.

**Comment by gff001** [comment]
### DUO ORCACA
**Pull request realizado no cód do ranking**
